Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Bad Request: /
"GET / HTTP/1.1" 400 68215
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
"GET /favicon.ico HTTP/1.1" 400 68135
Watching for file changes with StatReloader
Invalid HTTP_HOST header: '127.0.0.1:5000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Bad Request: /
"GET / HTTP/1.1" 400 68215
Invalid HTTP_HOST header: '127.0.0.1:5000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
"GET /favicon.ico HTTP/1.1" 400 68135
"GET / HTTP/1.1" 200 1169
Not Found: /favicon.ico
"GET /hamma/signup/ HTTP/1.1" 200 2503
Not Found: /favicon.ico
"GET /hamma/user_login/ HTTP/1.1" 200 1671
Not Found: /favicon.ico
"POST /hamma/user_login/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 1132
"GET /admin HTTP/1.1" 301 0
"GET /admin/ HTTP/1.1" 200 3724
"GET /static/admin/css/base.css HTTP/1.1" 200 16378
"GET /static/admin/css/dashboard.css HTTP/1.1" 200 412
"GET /static/admin/css/responsive.css HTTP/1.1" 200 18052
"GET /static/admin/css/fonts.css HTTP/1.1" 200 423
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
"GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
"GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
"GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
"GET /admin/hamma/usuario/ HTTP/1.1" 200 3180
"GET /static/admin/js/core.js HTTP/1.1" 200 5723
"GET /static/admin/css/changelists.css HTTP/1.1" 200 6190
"GET /static/admin/js/urlify.js HTTP/1.1" 200 8941
"GET /static/admin/js/jquery.init.js HTTP/1.1" 200 363
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 280364
"GET /admin/jsi18n/ HTTP/1.1" 200 3223
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 6918
"GET /static/admin/js/actions.js HTTP/1.1" 200 6766
"GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1530
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 128820
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
"GET /admin/hamma/ HTTP/1.1" 200 2441
"GET /admin/ HTTP/1.1" 200 3724
"GET /admin/auth/user/ HTTP/1.1" 200 7889
"GET /admin/jsi18n/ HTTP/1.1" 200 3223
"GET /static/admin/img/icon-no.svg HTTP/1.1" 200 560
"GET /static/admin/img/search.svg HTTP/1.1" 200 458
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
"GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
"POST /admin/auth/user/ HTTP/1.1" 200 3609
"GET /static/admin/js/cancel.js HTTP/1.1" 200 409
Internal Server Error: /admin/auth/user/
Traceback (most recent call last):
  File "/usr/local/lib64/python3.7/site-packages/django/db/backends/base/base.py", line 243, in _commit
    return self.connection.commit()
sqlite3.IntegrityError: FOREIGN KEY constraint failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib64/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib64/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib64/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib64/python3.7/site-packages/django/contrib/admin/options.py", line 607, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/django/contrib/admin/sites.py", line 231, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/django/contrib/admin/options.py", line 1720, in changelist_view
    response = self.response_action(request, queryset=cl.get_queryset(request))
  File "/usr/local/lib64/python3.7/site-packages/django/contrib/admin/options.py", line 1390, in response_action
    response = func(self, request, queryset)
  File "/usr/local/lib64/python3.7/site-packages/django/contrib/admin/actions.py", line 40, in delete_selected
    modeladmin.delete_queryset(request, queryset)
  File "/usr/local/lib64/python3.7/site-packages/django/contrib/admin/options.py", line 1091, in delete_queryset
    queryset.delete()
  File "/usr/local/lib64/python3.7/site-packages/django/db/models/query.py", line 722, in delete
    deleted, _rows_count = collector.delete()
  File "/usr/local/lib64/python3.7/site-packages/django/db/models/deletion.py", line 338, in delete
    sender=model, instance=obj, using=self.using
  File "/usr/local/lib64/python3.7/site-packages/django/db/transaction.py", line 232, in __exit__
    connection.commit()
  File "/usr/local/lib64/python3.7/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/django/db/backends/base/base.py", line 267, in commit
    self._commit()
  File "/usr/local/lib64/python3.7/site-packages/django/db/backends/base/base.py", line 243, in _commit
    return self.connection.commit()
  File "/usr/local/lib64/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib64/python3.7/site-packages/django/db/backends/base/base.py", line 243, in _commit
    return self.connection.commit()
django.db.utils.IntegrityError: FOREIGN KEY constraint failed
"POST /admin/auth/user/ HTTP/1.1" 500 157754
"GET /admin/ HTTP/1.1" 200 4483
"GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 200 392
"GET /admin/auth/user/ HTTP/1.1" 200 7889
"GET /admin/jsi18n/ HTTP/1.1" 200 3223
"POST /admin/auth/user/ HTTP/1.1" 200 3342
"POST /admin/auth/user/ HTTP/1.1" 302 0
"GET /admin/auth/user/ HTTP/1.1" 200 7590
"GET /admin/jsi18n/ HTTP/1.1" 200 3223
"POST /admin/auth/user/ HTTP/1.1" 200 3346
"POST /admin/auth/user/ HTTP/1.1" 302 0
"GET /admin/auth/user/ HTTP/1.1" 200 7167
"GET /admin/jsi18n/ HTTP/1.1" 200 3223
Not Found: /favicon.ico
"POST /admin/auth/user/ HTTP/1.1" 200 3350
Internal Server Error: /admin/auth/user/
Traceback (most recent call last):
  File "/usr/local/lib64/python3.7/site-packages/django/db/backends/base/base.py", line 243, in _commit
    return self.connection.commit()
sqlite3.IntegrityError: FOREIGN KEY constraint failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib64/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib64/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib64/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib64/python3.7/site-packages/django/contrib/admin/options.py", line 607, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/django/contrib/admin/sites.py", line 231, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/django/contrib/admin/options.py", line 1720, in changelist_view
    response = self.response_action(request, queryset=cl.get_queryset(request))
  File "/usr/local/lib64/python3.7/site-packages/django/contrib/admin/options.py", line 1390, in response_action
    response = func(self, request, queryset)
  File "/usr/local/lib64/python3.7/site-packages/django/contrib/admin/actions.py", line 40, in delete_selected
    modeladmin.delete_queryset(request, queryset)
  File "/usr/local/lib64/python3.7/site-packages/django/contrib/admin/options.py", line 1091, in delete_queryset
    queryset.delete()
  File "/usr/local/lib64/python3.7/site-packages/django/db/models/query.py", line 722, in delete
    deleted, _rows_count = collector.delete()
  File "/usr/local/lib64/python3.7/site-packages/django/db/models/deletion.py", line 338, in delete
    sender=model, instance=obj, using=self.using
  File "/usr/local/lib64/python3.7/site-packages/django/db/transaction.py", line 232, in __exit__
    connection.commit()
  File "/usr/local/lib64/python3.7/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/django/db/backends/base/base.py", line 267, in commit
    self._commit()
  File "/usr/local/lib64/python3.7/site-packages/django/db/backends/base/base.py", line 243, in _commit
    return self.connection.commit()
  File "/usr/local/lib64/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib64/python3.7/site-packages/django/db/backends/base/base.py", line 243, in _commit
    return self.connection.commit()
django.db.utils.IntegrityError: FOREIGN KEY constraint failed
"POST /admin/auth/user/ HTTP/1.1" 500 157434
Not Found: /favicon.ico
"GET /admin/ HTTP/1.1" 200 5209
"GET /admin/auth/group/ HTTP/1.1" 200 3510
"GET /admin/jsi18n/ HTTP/1.1" 200 3223
"GET /admin/ HTTP/1.1" 200 5209
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/gmontalvoy/Desktop/AlfredOnGitHub/tool/tool/tool/settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
